In [1]:
import numpy as np

In [2]:
a=np.zeros((3,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
b=np.ones((2,2),dtype=int)
b

array([[1, 1],
       [1, 1]])

In [48]:
a=np.array([1,2,3,4,5,6,7,8,9])
for i in a:
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

In [5]:
n=int(input("enter the size"))
arr=np.zeros(n,dtype=int)
for i in range(n):
    arr[i]=int(input("Enter the value:"))
print(arr)

enter the size3
Enter the value:1
Enter the value:2
Enter the value:3
[1 2 3]


In [23]:
x=np.array([1,2,3,2,4,1,1,5])
dic={}
for i in x:
    if i not in dic:
        dic[i]=1
    else:
        dic[i]+=1
for a,b in dic.items():
    print(a,'-',b)

1 - 3
2 - 2
3 - 1
4 - 1
5 - 1


In [17]:
import collections as col
x = np.array([1,2,3,3,9,1,3,1,9,7,10,1])
counter = col.Counter(x)
print(counter)

Counter({1: 4, 3: 3, 9: 2, 2: 1, 7: 1, 10: 1})


In [7]:
a=np.array([1,2,4,7,8,1,2,4,23,5])
n=int(input("Enter the value:"))
np.count_nonzero(a==n)

Enter the value:2


2

In [29]:
arr=np.array([1,2,3,3,4,5,6,7,8,9])
np.count_nonzero(arr<4)

4

In [30]:
arr=np.array([1,2,3,3,4,5,6,7,8,9])
len([i for i in arr if i<4])

4

In [41]:
arr=np.array([1,2,3,1,2,3,4,2,3,1,5,6,7,1,2,3,4,2,3,10,3,7])
dic=col.Counter(arr)
print(dic)
print([a for a,b in dic.items() if b<4])

Counter({3: 6, 2: 5, 1: 4, 4: 2, 7: 2, 5: 1, 6: 1, 10: 1})
[4, 5, 6, 7, 10]


In [32]:
arr=np.array([3,5,1,7,9,3])
n=int(input("Enter the value:"))
print(n in arr)

Enter the value:5
True


In [33]:
arr=np.random.randint(3,25,10)
print(arr)
print(np.min(arr),np.max(arr))

[10  4  8 12 20 22 19  8  6 16]
4 22


In [34]:
arr=np.array([3,7,1,7,3,1,5,2,9,4,6,12,43,16])
n=int(input("No.of values:"))
a=np.zeros(n,dtype=int)
print("Enter the value:")
for i in range(n):
    a[i]=int(input())
for i in a:
    print(i,'-',i in arr)

No.of values:3
Enter the value:
2
8
4
2 - True
8 - False
4 - True
